uplode_t3_t4
asifnaseebi/barq_weather_task pull request #3
Opened 2023-03-17 13:07 UTC by asifnaseebi

2023-03-17 17:41 UTC, Hamma111 requested changes

2023-03-17 17:41 UTC, Hamma111 commented on task/t3.txt
> +And from him I learned different commands
for it*

2023-03-17 17:41 UTC, Hamma111 commented on task/t3.txt
> +And from him I learned different commands
him is used for males. it is used for things

2023-03-17 17:41 UTC, Hamma111 commented on task/t4.txt
> +Switching from one file to another is easy۔
how do we save the file? you were supposed to explain that

2023-03-18 06:33 UTC, Hamma111 approved these changes

2023-03-18 10:48 UTC, merged

2023-03-18 10:49 UTC, asifnaseebi commented
t3,t4[18march]